### ISSUE TITLE
Count variable in buildFilter does not work

### ISSUE THREAD

**Issue by DavidCADanneels** [nemerosa/ontrack#1170]
The **count** parameter in the **standardFilter** for builds does not seem to work.

If I run this:
```
def baseBranch = ontrack.branch('SPEEDBOAT', '15.1')
def baseBuilds = baseBranch.standardFilter count: 20, withPromotionLevel: 'COPPER'
println "baseBuilds: ${baseBuilds.size()}"
```
the output is always
```
baseBuilds: 10
```
even if there are more COPPER builds in this branch.

The **count** value is always 10 (default)

The documentation for **3.43.25** still mentions this a valid example.

This issue popped up after the upgrade from 3.35.17 to 3.43.25

**Comment by DavidCADanneels** [comment]
We have found a workaround by using **graphQLQuery**:
```
def builds = ontrack.graphQLQuery(\'\'\'
{
    builds(project: "SPEEDBOAT", branch: "15.1", buildBranchFilter: {count: 20, withPromotionLevel: "COPPER"}) {
        name
    }
}
\'\'\').data.builds
```
This construct respects the request **count**

**Comment by dcoraboeuf** [comment]
Excellent!

The GraphQL API, esp. starting from the V4, is a first-class component of Ontrack.

The DSL that you were using in the initial description is being phased out: supported in V3 and V4, but removed in V5.

Also, if you're using Jenkins, I'd recommend, starting from V4, to switch to the Jenkins pipeline library - https://github.com/nemerosa/ontrack-jenkins-cli-pipeline - which is way more flexible than using the difficult to maintain Ontrack Jenkins plugin.

For other engines than Jenkins, you can use the:

* for GitHub, the Ontrack GitHub ingestion - https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#integration-github-ingestion
* for GitLab, the Ontrack GitLab pipeline - https://github.com/nemerosa/ontrack-gitlab-pipeline
* for any other use case, the Ontrack CLI - https://github.com/nemerosa/ontrack-cli - or directly the GraphQL API

Can I consider this ticket closed?

**Comment by DavidCADanneels** [comment]
Yes, you can close it.
I will have a look at the provided documentation links
