### ISSUE TITLE
GitLab configuration not possible through UI

### ISSUE THREAD

**Issue by maciejwajda** [nemerosa/ontrack#1217]
Found on ontrack `4.8.14`.

When navigating in the UI to GitLab configuration `ONTRACK_URL/#//extension/gitlab/configurations`, we don't see `Create a configuration` button (or any other), it just holds the list of the configurations.

The same applies for other configurations: JIRA, Git, Jenkins, GitHub, SonarQube, TFC, Artifactory, Bitbucket. 

When entering those configuration pages we get this `ui-error` error:
```
java.lang.IllegalStateException: Failed to create proxy for controller method return type: public net.nemerosa.ontrack.model.support.ConnectionResult net.nemerosa.ontrack.extension.gitlab.GitLabController.testConfiguration(net.nemerosa.ontrack.extension.gitlab.model.GitLabConfiguration)       
```

**Comment by dcoraboeuf** [comment]
Available in 4.8.35
