### ISSUE TITLE
Auto-versioning problem when updating same file

### ISSUE THREAD

**Issue by tomaszmariasik** [nemerosa/ontrack#1364]
In my setup I am using auto-versioning to update 2 entries within 1 application configuration file.

Here is simplified application configuration
[app.txt](https://github.com/user-attachments/files/18006716/app.txt)

To update targetRevision here I use below auto-versioning configuration:

`  - project: dxx-axx
    branch: main
    promotion: GOLD
    path: apps/dxx-nxx/dxx-nxx-dxx.yaml
    propertyType: "yaml"
    property: "#root[0].spec.generators.^[list != null].list.elements.^[name == 'dxx-nxx-e2e'].targetRevision" 
    additionalPaths:
      - path: apps/dxx-nxx/dxx-nxx-dxx.yaml
        propertyType: "yaml"
        property: "#root[0].spec.generators.^[list != null].list.elements.^[name == 'dxx-nxx-latest'].targetRevision"`

In auto-versioning PR I see two commits targetting included file:
1. First one is updating `dxx-nxx-e2e` targetRevision.
2. Second one is updating `dxx-nxx-latest` targetRevision but also is reverting update that is coming from commit no 1.

The outcome is that only one property is updated in the PR when I'd need two of them to be updated.

My thinking is that before second commit is made branch is not updated with changes coming from commit 1. If that was done then only relevant line would be updated in commit 2.

Please help.

**Comment by dcoraboeuf** [comment]
Available in 4.10.11
