### ISSUE TITLE
Centralize user/password management.

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#147]
Add central management for user/password could be a good improvement especially if user need to create multiple configuration with same user/password (like git or github).

**Comment by dcoraboeuf** [comment]
@flesire, do we still need this? Github and Stash configurations are now centralised, in 2.14.

**Comment by flesire** [comment]
If it's done for stash, it's ok for me.

**Comment by dcoraboeuf** [comment]
Similar function in GitHub and Stash configurations (see #300)
