### ISSUE TITLE
Memory leak / high cpu

### ISSUE THREAD

**Issue by theunb** [nemerosa/ontrack#197]
The page that shows a branch uses 1 cpu completely when you select a filter that shows 100 builds. Using chrome I verified that the page initially takes 70mb and after a while it went to 350mb. Also one cpu is at 100% (cfr ontrack-cpu-mem).
![ontrack-cpu-mem](https://cloud.githubusercontent.com/assets/10063424/5451415/3d1b03c4-8510-11e4-8f82-73f97c6a9804.png)

Ideas: 
- do not reload page (or builds) when previous builds are still refreshing.
- limit the amount of parallel asynch requests to the server

**Comment by dcoraboeuf** [comment]
On a heavy branch (with many builds and validation stamps), this also causes a high consumption of connections on the server side.
