### ISSUE TITLE
Validation stamp filter

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#242]
It's not possible for a logged user to filter out some validation stamps from the branch view.

A pipeline like 
![image](https://cloud.githubusercontent.com/assets/1262565/6247978/098b1056-b77b-11e4-8f0a-e2d6b5e673e2.png)

could be a problem on small screen.

**Comment by dcoraboeuf** [comment]
Nice screenshot :) It's indeed missing. I'll try to put it in version 2.5, or at worse, 2.6.

**Comment by dcoraboeuf** [comment]
I'll store the filtering at client level (browser).
