### ISSUE TITLE
Auto-promote of promotion levels is not available anymore

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#254]
It's should be possible to create rules that allow automatic promotion levels.

**Comment by flesire** [comment]
Configuration 'manage promotion levels':
![image](https://cloud.githubusercontent.com/assets/1262565/6571340/b07f9774-c707-11e4-8e45-08ec913907f7.png)



Promotion level view :
![image](https://cloud.githubusercontent.com/assets/1262565/6571316/5333bece-c707-11e4-8bf8-48ece9f10c44.png)

**Comment by dcoraboeuf** [comment]
Implementation will be based on _promotion rules_: a given configurable rule can be attached to a promotion level.

Promotion based on a list of validation stamps is just a promotion rule like any other.

When to trigger a rule? Trigger based on events, need for a new event listener concept. Is that generic enough?

Is that possible to run promotion rules outside of events? Probably not - we do not want to change the past.
