### ISSUE TITLE
SVN branch property can't be deleted

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#256]
It's impossible to delete the property 'SVN branch' on a branch even if i'm logged as administrator.

Ontrack version : 2.6.0

**Comment by dcoraboeuf** [comment]
Do you have any stack trace?

**Comment by flesire** [comment]
Nothing on the log but if i have this on the UI :

![image](https://cloud.githubusercontent.com/assets/1262565/6616441/461e5246-c8ae-11e4-8a50-0a9b3791e98f.png)

**Comment by dcoraboeuf** [comment]
Have you a SVN property at project level?

**Comment by flesire** [comment]
I deleted to see if it delete the corresponding properties but it's not the case. So i re-added it but this action not enable the delete for the branch property.

**Comment by dcoraboeuf** [comment]
Yes indeed - the possibility to edit a SVN _branch_ property is linked to the presence of the SVN _project_ property.
