### ISSUE TITLE
Git : Authentication doesn't work for http protocol

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#259]
It's not possible to use a git server via http although https works fine.

Stack trace message :
'http://<server/repo : authentication not supported'

Try to pass user:password directly on the URL but doesn't work.

**Comment by dcoraboeuf** [comment]
Any idea how I could test this?

**Comment by flesire** [comment]
I can test it or you can create a test git repository access via http

**Comment by dcoraboeuf** [comment]
The problem is that I'd like to reproduce the problem before I can actually correct it :( Can you debug and collect more information?

**Comment by flesire** [comment]
Actually i already debug GitRepositoryClientImpl class where the problem occured but no more information. The problem could be that JGit doesn't support user/password authentication for HTTP protocol. I do a simple java project with jgit to test and i had the same problem.

**Comment by dcoraboeuf** [comment]
Ok, so it seems like a defect in JGit, and not in Ontrack. Is there any existing ticket in JGit? Ontrack is using version `3.5.1.201410131835-r`

**Comment by flesire** [comment]
found this one : https://bugs.eclipse.org/bugs/show_bug.cgi?id=296201

**Comment by dcoraboeuf** [comment]
Fix included (0.11).

**Comment by flesire** [comment]
Actually, the problem is due to our installation of stash and is not related to ontrack. I found a way to fix the problem so i have the connection to our git/stash instance.
