### ISSUE TITLE
It should be possible to save multiple validation stamp filter.

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#265]
Allow user to save different filter for validation stamps to be able to have multiple view on a validation pipeline could be a great addition.

**Comment by flesire** [comment]
No news on that one ? We have validation pipeline with a lot of validation and i would like to be able to create different views with subset of the validation pipelines (for example have subset of validation stamps per promotion level).

**Comment by dcoraboeuf** [comment]
Hi Fabien,

How do you imagine this? As additional options in the "Filter validation stamps" dialog? In this case, I'd put this in a separate page. I'd also choose to make this valid for _all_ branches, not only this one.

Any other input or comment? As for any activity on this topic, difficult to set a date :( Maybe end of February for the 2.30?

**Comment by MorganGeek** [comment]
It would definitely help to avoid repetitive actions and allow to save different views adapted to different needs. Useful for quick information sharing, and potentially it would improve performance by loading less information

**Comment by dcoraboeuf** [comment]
@flesire , @MorganGeek , what do you think about the tasks below? I was thinking of using a general concept of _validation stamp filter_ editable globally, as simple list of names associated with name patterns. At least in my current context, we have more than 1000 branches and such global edition makes more sense. But I need to have your opinion as well. It does not prevent the fact that I can allow edition at project & branch level as well.

- [ ] Model for the validation stamp filters (independent on any project or any branch) - just a name and a list of patterns
- [ ] Edition of validation stamp filters globally
- [ ] Edition of validation stamp filters at project level (restricting the selectable validation stamps to the current project)
- [ ] Edition of the validation stamp filters at branch level (restricting the selectable validation stamps to the current project)
- [ ] Selection of the validation stamp filter in the branch view
- [ ] The validation stamp filter can be specified as a URL parameter for the branch view

**Comment by MorganGeek** [comment]
it seems ok for me ;)

**Comment by dcoraboeuf** [comment]
Going on then...

**Comment by dcoraboeuf** [comment]
Ok, done. I'll integrate the branch soon into the `master`. The release will be available end of May.

**Comment by MorganGeek** [comment]
Excellent news ! Thanks for the work ! Can't wait to test that :+1:

**Comment by dcoraboeuf** [comment]
Documentation available at https://github.com/nemerosa/ontrack/blob/master/ontrack-docs/src/docs/asciidoc/usage-validation-stamp-filters.adoc - will be part of release 2.30 (end of May or even before).

**Comment by dcoraboeuf** [comment]
Available in 2.30.0 - see https://nemerosa.ghost.io/2017/05/09/ontrack-2-30-and-3-0/
