### ISSUE TITLE
Git test failed.

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#271]
When i tried to build latest code from the master, the build failed with the following exception :

net.nemerosa.ontrack.git.support.GitRepositoryClientImplTest > Tag containing a commit FAILED
    net.nemerosa.ontrack.common.ProcessExitException at GitRepositoryClientImplTest.groovy:152

and more specifically in the test result file :

net.nemerosa.ontrack.common.ProcessExitException: error: malformed object name 9     9d332c
   9 1356dd4

Apparently the test try to run 'tag' command with two commits separated by a carriage return.

Git 2.1.4 is installed in the system and it seems that the build doesn't failed on system with older version of Git (test on macosx 10.9 with Git 1.9).

**Comment by dcoraboeuf** [comment]
On MacOS, using Git 2.4.0, I do not have this problem.

On the Jenkins build, I'm using Git 1.9.0. I'll try to update and test.

On which system do you have the problem?

**Comment by flesire** [comment]
Ubuntu vivid with Git 2.1.4 and it build without problem on macosx with a Git 1.7.x.

**Comment by dcoraboeuf** [comment]
I'll see if I can test on a local Ubuntu VM.

**Comment by flesire** [comment]
Is it possible the problem is due to a missing/wrong global git config. I already had the problem with a new installation where 11 tests failed for git because no user.email and user.name global config are defined.

**Comment by dcoraboeuf** [comment]
Do I close this ticket?

**Comment by flesire** [comment]
No, I've tested on 2 different systems (Ubuntu and Centos) and two git versions (1.8.3 and 2.1.4) and i've always reproduce the problem.

**Comment by dcoraboeuf** [comment]
Ok, I'll try to test on a Ubuntu VM.

**Comment by dcoraboeuf** [comment]
I'll take the opportunity to define a controlled and versioned build environment using Docker, which I can then use for reference and build environment in Jenkins.

**Comment by dcoraboeuf** [comment]
* Bower and Grunt run now using the Gradle Node plugin
* Git integration tests have a problem with the current user identity
   * need to move the Git test repos to the build directory (in `/tmp` now)
   * need to check the Git commit command for options
