### ISSUE TITLE
Link 2 issue trackers to the same git repository

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#273]
We have some projects hosted remotely but issues are put in 2 different jira instances. Is it possible to link 2 issues trackers to one scm repository to be able to have a complete changelog ?

**Comment by dcoraboeuf** [comment]
You can declare two different repositories.

**Comment by flesire** [comment]
But for a project in Ontrack you can only add 1 git repository configuration. My goal is to link one project to one git repository linked to 2 different issues trackers.

**Comment by dcoraboeuf** [comment]
That would either imply some refactoring or the creation of an issue service which can aggregate other issue services. What do you think?

**Comment by flesire** [comment]
The solution with a service that aggregate issue trackers seems the best solution with minimal impact on the current structure of Ontrack.

**Comment by dcoraboeuf** [comment]
Ok, I'll try to see this for the next version (planned for end of June).

**Comment by dcoraboeuf** [comment]
Fabien, do you think you could build and test the `feature/274-combined-issue-service` branch? It has an additional issue service available, accessible through the admin menu, "Combined issue service management", which allows you to declare an issue service based on other ones.

Can you try and test? Thanks.

**Comment by flesire** [comment]
I test it this morning and it works perfectly as i can see the issues from all the issue trackers. But the issue number is not a link anymore, is it the expected behavior ?

**Comment by dcoraboeuf** [comment]
No, it should indeed be a link. I'll look into it.

**Comment by dcoraboeuf** [comment]
* [ ] Extract the combined issue service as a separate extension (it is today in the core issues module)

**Comment by dcoraboeuf** [comment]
@flesire, I have corrected the issue link. It should be there when available.

Generally speaking, the combined issue service has to work on issue _common features_ only, so the amount of information which can be displayed is limited.

**Comment by dcoraboeuf** [comment]
Can you test and tell me? I wish to make an early release (before June 30th as initially planned).

**Comment by dcoraboeuf** [comment]
Unless there is a blocking issue, I'll probably release a 2.10.0 Ontrack this week-end and this feature would be available in the 2.11.0 at the end of June.

**Comment by dcoraboeuf** [comment]
Postponing this issue to next release - 2.11

**Comment by dcoraboeuf** [comment]
@flesire , I have moved the combined issue service to its own extension - will you be able to test?

**Comment by flesire** [comment]
I tested it and works perfectly. Can be included in 2.12 release if possible.

**Comment by dcoraboeuf** [comment]
Good news. I can release the 2.12 this week, including other features.
