### ISSUE TITLE
Ontrack database always recreated at startup

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#299]
Since 2.13.9, each time ontrack is restarted, the database is recreated. I use the following command line :
 
_nohup /opt/jvm/current/bin/java -jar ontrack.jar --spring.profiles.active=prod --server.port=9082 > ontrack.log &_

Is there a change on the parameters to run the application ?

**Comment by dcoraboeuf** [comment]
The datasource path is indeed no longer specified in the package and you have to specify it in the parameters using:

```
--spring.datasource.url=jdbc:h2:/var/ontrack/data/database/data
```

Note that the path can also be relative (using `.`) to the JAR. I'll document this in the Wiki later on.

**Comment by flesire** [comment]
Works fine, thanks :+1:

**Comment by dcoraboeuf** [comment]
Documentation added in https://github.com/nemerosa/ontrack/wiki/Standalone%20installation
