### ISSUE TITLE
Git Stash support

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#300]
Although it is possible to define a Git configuration which points to a Stash repository, configuring several repositories will require a multiplication of the repository configurations.

Define a Stash configuration once, and configure a project by defining the repository in the Stash instance.

Actions:

* [x] Stash configurations
* [x] Stash project configuration
* [x] Test of the Stash configuration
* [x] Indexation of the Stash repository at global level
* [x] Issue service at global level
* [x] DSL global configuration
* [x] DSL project configuration

**Comment by flesire** [comment]
This feature will definitely simplify my life :+1:

**Comment by dcoraboeuf** [comment]
@flesire, I plan to make it available in September only :) with the 2.14. Holidays...

**Comment by dcoraboeuf** [comment]
@flesire, the main work is now done on the `feature/300-stash`. Feel free to test while I'm away. Your feedback is more than welcome.

**Comment by dcoraboeuf** [comment]
1. Create a Stash configuration
1. Configure your project
1. Configure (optionally) your branch (`master` by default)

If needed, configure your [certificates](https://github.com/nemerosa/ontrack/wiki/Certificates).

**Comment by dcoraboeuf** [comment]
DSL documented at https://github.com/nemerosa/ontrack/wiki/DSL-Config-Stash and https://github.com/nemerosa/ontrack/wiki/DSL-Property-Stash-Project
