### ISSUE TITLE
Display of branch with lot of validation stamps is messy

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#391]
Since 2.18.0, display of branch with lot of validation stamps is really a mess :
![image](https://cloud.githubusercontent.com/assets/1262565/13218857/86c97cb0-d96c-11e5-9571-227828d07f16.png)

We can zoom out but the screen become unreadable.

Possible solutions (just ideas not sure is feasible) could be to :
- Merge the jenkins icon and the weather icon.
- Allow people to save different validation stamp filter for the same branch.
- Use an icon only version of the promotion levels.
- Use row selection instead of radio buttons.

**Comment by dcoraboeuf** [comment]
Has it been better in version 2.17?

**Comment by dcoraboeuf** [comment]
Would it be OK to make the validation columns scrollable? There's just too much information on this page to have a compact layout. For cases where the number of validation stamps is not so high, the default layout would be still OK.

**Comment by flesire** [comment]
I upgraded directly from 2.13 to 2.18 :smile: but one difference we see directly is the weather icon was on top of the jenkins icon before and now it is next to the jenkins icon so there are more blanks between columns.

**Comment by dcoraboeuf** [comment]
Issues #397 and #399 should already improve the performances quite a lot. They are available right now on the `master` branch and will be released with 2.20. I'll keep working on reducing the load on the client side.

**Comment by MorganGeek** [comment]
It would be great to let the user play with multiple validation stamp filters, sometimes we don't want to see all stamps but just a summary.

**Comment by dcoraboeuf** [comment]
So somehow linked to #265 ?

**Comment by MorganGeek** [comment]
not totally mad :) I would also like to see gui / enhancement labels assigned to the issue in this case, do you agree ?

**Comment by dcoraboeuf** [comment]
Done :)

Now, I really lack time to work on Ontrack nowadays. But it's not forgotten. After all, it's heavily used at my client.

**Comment by dcoraboeuf** [comment]
- [x] Merge the jenkins icon and the weather icon - weather icon gone since 2.17
- [ ] Allow people to save different validation stamp filter for the same branch - will be done with #265
- [ ] Use an icon only version of the promotion levels - easy to do, will do. The text has indeed no added value
- [ ] Use row selection instead of radio buttons - will do

**Comment by MorganGeek** [comment]
Excellent :-)

**Comment by dcoraboeuf** [comment]
@flesire , @MorganGeek , selecting a row on click is really easy, but the idea here is to select a range of builds in order to have a change log. I do not see how we can achieve this without selecting two boundaries explicitly. Any idea?

**Comment by dcoraboeuf** [comment]
I could of course allow the user to select any row, and the range is then defined by the top-most and bottom-most selection, but that'd look a bit awkward...

**Comment by dcoraboeuf** [comment]
I can also propose click / shift-click to define a range.

**Comment by flesire** [comment]
The shift + click seems the best solution.

**Comment by dcoraboeuf** [comment]
@flesire , @MorganGeek , any comment before I release (target 2.30.1 & 3.0.1)? See the documentation in commit f7dabd0f584cd985d08de547c7a66ac56601f767 ?

**Comment by dcoraboeuf** [comment]
On the way to 2.30.1 & 3.0.1...
