### ISSUE TITLE
LDAP Configuration Examples and AD integration

### ISSUE THREAD

**Issue by jeebitesh** [nemerosa/ontrack#446]
Can you please provide some example in documentation, what are the values you are expecting and in which format. This is is "nice to have" and eliminates any confusion related to configuration part. Should be descriptive type or below text boxes or provide feature like Jenkins (?).

It would be great if you can also include AD Integration which can ease things on Windows Server.

**Comment by dcoraboeuf** [comment]
I'll document the LDAP integration. It works also fine with AD - I'm using it for a long time now.

Generally speaking, I'm trying to catch up with the documentation and that's a long running effort :(

I do not plan any native AD integration directly, but PR are welcome :)

**Comment by dcoraboeuf** [comment]
Will be available in 2.24.2.

Note that I've put the inline help in the LDAP configuration screen and that the documentation now includes an example + AD notes.

**Comment by dcoraboeuf** [comment]
New documentation [available](http://nemerosa.github.io/ontrack/release/2.24.2/doc/index.html#ldap)
