### ISSUE TITLE
Jenkins detect vulnerability

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#506]
Ontrack Plugin
SECURITY-495

This plugin allows users with Job/Configure permission to run arbitrary Groovy code inside the Jenkins JVM using the Ontrack DSL feature, effectively elevating privileges to Overall/Run Scripts.

As of publication of this advisory, there is no fix.

**Comment by dcoraboeuf** [comment]
Duplicate of https://github.com/jenkinsci/ontrack-plugin/issues/27

**Comment by flesire** [comment]
Forgot to check the plugin site, sorry :)

**Comment by dcoraboeuf** [comment]
Fixed in plugin 2.30.5
