### ISSUE TITLE
The permalink for build searches does not trigger searches

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#524]
Hi,
Using Ontrack v2.30.4 : The build searches page displays a permalink, which should be used to trigger the exact same search. Unfortunately, after using the link to run a search, no search is triggered. 

Examples of generated permalinks : 

* Build search with BRONZE promotion level
http://192.168.126.76:9082/#/build-search/101#%7B%22maximumCount%22:10,%22promotionName%22:%22BRONZE%22%7D 

* Build search without any parameter 
http://192.168.126.76:9082/#/build-search/101#%7B%22maximumCount%22:10,%22promotionName%22:%22%22%7D

Cheers,
M.

**Comment by dcoraboeuf** [comment]
Thanks for the ticket. I'll work on it when I'm back from holiday.

**Comment by MorganGeek** [comment]
Thanks ! Enjoy your holidays

**Comment by dcoraboeuf** [comment]
Fixed, and I'll launch the release process for 2.30.9, but I get many problems with the publication on the Maven Central, so this can be delayed... Stay tuned.

**Comment by MorganGeek** [comment]
Good luck and continuation for that :) , and many thanks for the resolution !

**Comment by dcoraboeuf** [comment]
Fix available in 2.30.9

**Comment by dcoraboeuf** [comment]
Fix available in 2.31.5
