### ISSUE TITLE
Switch option appears multiple times

### ISSUE THREAD

**Issue by DavidCADanneels** [nemerosa/ontrack#556]
If you keep a project page open for a long time, the last option in the list (here 'Switch') is displayed multiple time. I assume: the longer you keep it open, the more it appears. See screenshot:
![image](https://user-images.githubusercontent.com/5195271/31217202-6659515a-a9b6-11e7-9f4b-40fb8484f137.png)
Note: I'm using Firefox as browser

**Comment by dcoraboeuf** [comment]
Already fixed by #551. Available in 2.32.7.
