### ISSUE TITLE
Bitbucket generating invalid configuration/links

### ISSUE THREAD

**Issue by alitheg** [nemerosa/ontrack#564]
When I create a bitbucket configuration pointing to https://bitbucket.org, it looks like the project gets an invalid link. If I add project XXX, repository YYY, the link on the project page in ontrack is https://bitbucket.org/projects/XXX/repos/YYY. I assume this is a Bitbucket Server URL (formerly Stash)?Bitbucket URLs are the account, then the repo name. "Projects" aren't included in the URL for Bitbucket, though I assume I should be using the user name (I tried leaving blank and entering XXX/YYY as the repo name, but the Save button was disabled).

**Comment by dcoraboeuf** [comment]
I've been using both BitBucket Cloud & Server (including old Stash instances), so I'm a bit surprised.

Can you please attach a screenshot of your BitBucket configuration?

Thanks,
Damien.

**Comment by alitheg** [comment]
Of course! There's a good chance I'm just doing something wrong - see below:

![screen shot 2017-10-26 at 11 07 24](https://user-images.githubusercontent.com/450789/32047505-0b3a522c-ba3e-11e7-8797-75000333f0b8.png)
![screen shot 2017-10-26 at 11 07 59](https://user-images.githubusercontent.com/450789/32047510-0d3e514a-ba3e-11e7-94b2-428140140181.png)
![screen shot 2017-10-26 at 11 08 09](https://user-images.githubusercontent.com/450789/32047517-14ec91a4-ba3e-11e7-80f3-4e5e8d3f45e1.png)

**Comment by dcoraboeuf** [comment]
Thanks! I'll have a look later.

**Comment by dcoraboeuf** [comment]
Fixed. It will be available in 2.33.0 (available on October 31st)
