### ISSUE TITLE
Add example of usage of ontrack in Jenkins declarative pipeline

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#574]
Hi,

While migrating from classic Jenkins jobs definition to Jenkins declarative pipeline definition, I'm looking for examples of usage of ontrack in and ontrack DSL in context of declarative pipelines.
 
I'm trying to create jobs parameters whose values are automatically populated by ontrack using ontrack DSL. It was possible to do so before declarative pipeline, using ontrack dsl parameter in the UI, but I didn't find an example of doing the same thing in declarative pipeline. 

Is it possible ? Could you provide an example if you have any ? A solution to my particular issue or even better, a complete example of declarative pipeline making use of the full potential of ontrack could be a good helper to convice more people to use ontrack, especially since declarative pipeline is the future of jenkins jobs definition.

Thanks a lot ! :)

Cheers
Morgan

**Comment by dcoraboeuf** [comment]
Hi Morgan,

This issue would be more suited in the jenkinsci/ontrack-plugin repository.

But in short 1) the solution does exist 2) it has not been released yet.

See the https://github.com/jenkinsci/ontrack-plugin/tree/feature/19-pipeline-dsl branch of the Ontrack Jenkins plug-in or the jenkinsci/ontrack-plugin#19 issue.

I'll try to see if I can spend a bit of time on this to polish everything up and release. Not so easy at the moment :(

Stay tuned,
Damien.

**Comment by MorganGeek** [comment]
Thanks for your quick feedback :) 
I'll create the issue on the other repository as you suggested. 

Cheers
Morgan

**Comment by dcoraboeuf** [comment]
The issue does exist (jenkinsci/ontrack-plugin#19), so maybe no need to create a new one, but you can add your comments :)

**Comment by MorganGeek** [comment]
Indeed ! thanks :) :+1:
