### ISSUE TITLE
My favorites

### ISSUE THREAD

**Issue by GrzegorzKaczan** [nemerosa/ontrack#632]
Hi,

I would like to propose a feature to be able to favorite a branch/project/build and see it on a home page, next to list of all projects.
This would create kind of personalized dashboard which i can use to track all of my points of interests at once without having to keep separate tabs (and need to search/open them each time).

Each `thing` Favorited should be possible to be shown in simplified way. Meaning i don't need all the steps of a branch's pipeline on my Home page, just the status of latest build, promotion level, timings etc.

**Comment by dcoraboeuf** [comment]
FYI, you can already select Projects as favourites. But it's sometimes too verbose, and your approach sounds more scalable.

To select a project as a favourite, click on a star on the left of its name. A "Favourites" section will then appear.

As mentioned, I think your idea is better. Any kind of [object](http://nemerosa.github.io/ontrack/release/latest/doc/index.html#model) should be selectable as a favourite.

**Comment by dcoraboeuf** [comment]
Management of issue tasks at https://trello.com/b/94JL16Lz/ontrack-632-favourites (ask for being invited)

**Comment by GrzegorzKaczan** [comment]
Particular build as fav? don't think so, as you said those are temporary things and removed from jenkins in rotation anyway.
What you wrote is exactly what i wanted, go for it.
