### ISSUE TITLE
Meta info data on Valdation stamps is limited to 200 characters

### ISSUE THREAD

**Issue by DavidCADanneels** [nemerosa/ontrack#639]
We are trying to add Meta Info on the Validation Stamps.
We noticed that all this info is saved in a single database entity and that the length of this value is growing each time we add meta info. The size of this database entity is limited to 200 characters, which is too short in our case.

This is the error we saw in the Ontrack logs:
```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [UPDATE PROPERTIES SET JSON = ?, SEARCHKEY = ? WHERE ID = ?];
Value too long for column "SEARCHKEY VARCHAR(200) SELECTIVITY 98": "'test:test;imageName:docker.clear2pay.com/imageName:1.0;na_base_image:docker.clear2pay.com/na_base_image:1.0.2-0-37-4ab8642;na_t... (214)"; SQL statement:
UPDATE PROPERTIES SET JSON = ?, SEARCHKEY = ? WHERE ID = ? [22001-196]; nested exception is org.h2.jdbc.JdbcSQLException: Value too long for column "SEARCHKEY VARCHAR(200) SELECTIVITY 98": "'test:test;imageName:docker.clear2pay.com/imageName:1.0;na_base_image:docker.clear2pay.com/na_base_image:1.0.2-0-37-4ab8642;na_t... (214)"; SQL statement:
UPDATE PROPERTIES SET JSON = ?, SEARCHKEY = ? WHERE ID = ? [22001-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:797)
	at org.h2.command.dml.Update.update(Update.java:125)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:354)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)
	at java.lang.Thread.run(Thread.java:748)
```
I see 2 possible solution here:
- extend the length of this field (how long?)
- add a cross reference table, so each separate meta link is a distinct entry in this new table and we can add as many links as we want.

**Comment by dcoraboeuf** [comment]
Hello David,

Properties are all using the same table for their storage, and I agree that this system is not very optimal, especially for this kind of multi purpose property. Refactoring this would however be consequent and should be done only on last release (3.x, Postgres based).

In the meantime, I see three main paths:

* increasing the field length - but as you mention, it's difficult to foresee how much one would need
* I know for fact :) that you're using a custom extension of Ontrack, and it might be worth it to consider [coding your own property definition](https://ams3-delivery-space.ams3.cdn.digitaloceanspaces.com/ontrack/release/latest/docs/doc/index.html#extending-properties). This way, you would have more flexibility.
* starting to extract properties in their own dedicated storage - as mentioned, doable, but costly in time, migration and impact ; I would not do this on a version 2.x (H2 based), only on 3.x

Tell me what you think.

Another question - which exact version do you currently use?

Thanks,
Damien

**Comment by dcoraboeuf** [comment]
I just thought about a fourth possibility: the "search key" column, as its name indicates, is used only for searches based on this property. We could just make sure to truncate the value before storing it. The search would not work (properly), but this would leave some time for a future refactoring of the properties storage.

**Comment by dcoraboeuf** [comment]
Hi @DavidCADanneels , have you had time to look at my proposals above? Thanks.

**Comment by dcoraboeuf** [comment]
I also got stuck with the storage for the meta info property. I got quite fast with the issues for 3.38 so I can squeeze this for the next release. But it would be for 3.x.

Still using 2.x I think?

**Comment by dcoraboeuf** [comment]
@DavidCADanneels , for 2.x, I could just make sure the storage does not fail, and truncate the search key if needed. Can you give me the exact version you're using?

**Comment by dcoraboeuf** [comment]
* For 2.x, just increasing the `search_key` column from 200 to 600, and making sure it is not exceeded
* In version 3.x, planned refactoring

**Comment by dcoraboeuf** [comment]
@DavidCADanneels , fix available in 2.35.1 (only 600 chars for the column + truncating if needed).

Real fix will be in 3.x

**Comment by DavidCADanneels** [comment]
Damien,

Our Extension is currently built on version 2.34.6, but I will upgrade it to the latest 2.x version.
We consider to migrate to 3.x, but I will need some help from my colleagues to migrate the data.

Sorry for the late reaction. I did not work on this topic, since I created this ticket. I was fully occupied with other work (translating Jenkins BuildFlows into Jenkins Pipelines and trying to setup a new Jenkins Master)

Perhaps we can meet each other soon for a New Year's lunch?

Note: I cannot access Trello from my Workstation (firewall, ...), I need to use my phone or other computer.

**Comment by DavidCADanneels** [comment]
It seems that the ontrack-extension-plugin does not exist for 2.35.1. In https://jcenter.bintray.com/net/nemerosa/ontrack/ontrack-extension-plugin I see that the latest version was 2.34.9

**Comment by dcoraboeuf** [comment]
1/ indeed, the change log from 2.34.6 to 2.35.1 (https://ontrack.nemerosa.net/#/extension/git/changelog?from=3718&to=4256) contains #603 (Migration to Micrometer) - the way metrics are managed is now aligned with Spring Boot 2.x (even if all versions of Ontrack are currently still using Spring 1.5, but this allowed a better management of tagged metrics). You can find more information about using the new metrics system at https://ams3-delivery-space.ams3.cdn.digitaloceanspaces.com/ontrack/release/2.35.0/docs/doc/index.html#monitoring-metrics

2/ I'll have a look for the delivery

**Comment by dcoraboeuf** [comment]
About the `ontrack-extension-plugin`, it is available in the Maven Central at https://search.maven.org/artifact/net.nemerosa.ontrack/ontrack-extension-plugin/2.35.1/jar - I'm not sure to know why you access it at JCenter. The mentioned repositories are documented at https://ams3-delivery-space.ams3.cdn.digitaloceanspaces.com/ontrack/release/2.35.0/docs/doc/index.html#extending-preparing

I hope this helps

Damien
