### ISSUE TITLE
Broken links in Ontrack documentation (README.md)

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#656]
Several links point to domain `nemerosa.github.io` while the content is served at `ams3-delivery-space.ams3.cdn.digitaloceanspaces.com`

### Examples : 
```
https://nemerosa.github.io/ontrack/release/latest/doc/index.html
https://nemerosa.github.io/ontrack/release/latest/doc/index.html#extending
https://nemerosa.github.io/ontrack/release/latest/doc/index.html#usage-github
https://nemerosa.github.io/ontrack/release/latest/doc/index.html#usage-bitbucket
https://nemerosa.github.io/ontrack/release/latest/doc/index.html#contributing
https://nemerosa.github.io/ontrack/release/latest/doc/index.html#usage-subversion
https://nemerosa.github.io/ontrack/release/latest/doc/index.html#usage-git
```

**Comment by dcoraboeuf** [comment]
Digital Ocean Space subdomains are now available and `static.nemerosa.net` is now available, for example https://static.nemerosa.net/ontrack/release/3.38.7/docs/doc/index.html.

I'll use this domain for the correction of references.

**Comment by dcoraboeuf** [comment]
I'll keep the ticket open for having the links on the web site to `static.nemerosa.net`
