### ISSUE TITLE
Propose Logo For Ontrack

### ISSUE THREAD

**Issue by mirzazulfan** [nemerosa/ontrack#666]
Hi, I am a graphic designer and opensource enthusiast, I wanted to contribute to your project by designing logo for your project. If you have an idea please share with me, it would be better for me. Best Regard!

**Comment by dcoraboeuf** [comment]
Hi,

There is already a logo - https://github.com/nemerosa/ontrack/blob/master/doc/logo-source.png

**Comment by mirzazulfan** [comment]
Oh great. If you need a logo for another project, I will help you. Regard.
