### ISSUE TITLE
Okta integration

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#668]
- login with Okta
- Okta application integration through OAuth

**Comment by dcoraboeuf** [comment]
See https://docs.spring.io/spring-security/site/docs/current/reference/html/jc.html#multiple-httpsecurity for implementing several HTTP securities?

**Comment by dcoraboeuf** [comment]
Done in version 4 - see #756

**Comment by MorganGeek** [comment]
Nice !
