### ISSUE TITLE
Editable comments

### ISSUE THREAD

**Issue by Pinio31** [nemerosa/ontrack#680]
As a user I would like to have the possibility to update my own comments

**Comment by dcoraboeuf** [comment]
I propose to allow the edition of comments to the following roles:

* PARTICIPANT are allowed to enter comments - they can edit their OWN comments
* PROJECT OWNER & MANAGERS can edit any comment in their managed project
* ADMINISTRATORS can of course edit any comment anywhere

@Pinio31 , OK with this?

**Comment by Pinio31** [comment]
perfect for me :)
