### ISSUE TITLE
Support for pull requests

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#690]
Only branches have been supported in Ontrack.

In Git projects, many things are also happening at pull request level and are not visible in Ontrack.

A pull request can be considered as a special type of branch (actually linking two other branches).

Pull requests could be managed:

* only for Git based projects
* using a special type of branch
* being disabled automatically when the PR is merged
* being deleted automatically when the PR is declined / deleted
* linking two branches together (source --> target)
* page to explore the graph of branch dependencies based on pull requests

**Comment by MorganGeek** [comment]
🥳
