### ISSUE TITLE
Typo in a link from the documentation for promotion levels

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#693]
In https://github.com/nemerosa/ontrack/blob/39b27fcef181f2270aadb3117d7d1ec82ad9b56b/ontrack-docs/src/docs/asciidoc/usage-promotion-levels.adoc there is a typo in `dependencues`, see below :

```
[[promotion-levels-checks-dependencues]]
===== Previous dependencies check
```

**Comment by dcoraboeuf** [comment]
Fixed by #694
