### ISSUE TITLE
How I can increase RAM size for Ontrack server? 

### ISSUE THREAD

**Issue by raj333921** [nemerosa/ontrack#708]
Is there any configuration for us to increase RAM size in our extension ? 
Can we override existing key org.gradle.jvmargs = -Xmx2048m because its available in base image ?
 Ontrack Version : 2.35.2

**Comment by dcoraboeuf** [comment]
Hi @raj333921 ,

I kind of understand that you're using Docker? If yes, in your extension image, you just have to set `JAVA_OPTIONS` environment variable to your particular settings. `JAVA_OPTIONS` will be passed to the JVM running Ontrack and your extension.

See https://github.com/nemerosa/ontrack/blob/release/2.35/docker/Dockerfile#L35 and its usage in https://github.com/nemerosa/ontrack/blob/release/2.35/docker/start.sh#L18

Also documented at https://github.com/nemerosa/ontrack/blob/release/2.35/ontrack-docs/src/docs/asciidoc/installation.adoc#basic-deployment

Best regards,
Damien
