### ISSUE TITLE
Can't launch ontrack in command line following the docs

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#721]
While working on the `develop` branch of ontrack, I'm following the documentation for launching the application from the command-line at https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#development-launch-gradle

The documentation instructs to run the following command 
`./gradlew :ontrack-ui:bootRun`

However, doing so gives the following error

``` 
> Configure project :
Using package version = 0.0.0

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':ontrack-ui:bootRun'.
> Task with path 'bootRepackage' not found in project ':ontrack-ui'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
```

The following command `./gradlew :ontrack-ui:tasks` 
shows a list of available tasks, which do not include `bootRepackage`

By replacing `bootRepackage` with `bootJar` in `ontrack-ui/build.gradle.kts`, situation looks better : 
```
...
BUILD SUCCESSFUL in 6m 35s
462 actionable tasks: 441 executed, 21 up-to-date
```

**Comment by dcoraboeuf** [comment]
Fixed by #722
