### ISSUE TITLE
Using Elasticsearch for searches

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#723]
The search engine in Ontrack does not rely on any index and is therefore particularly slow. By using a search index like Elasticsearch, we can make this search way more efficient and even allow, out of the box, more structured searches.

This can be achieved in several steps:

* decide if we want to have Elasticsearch by default or as an option - the former would be a big change in terms of installation and would require a version 4, whereas the latter, which could still rely on the default (slow) engine by default, would just be a feature flag away. The latter solution would also be more complex to implement.
* if Elasticsearch is enabled (by default or as an option), following changes would be needed:
** search providers would have to provide an index definition for the data they index
** registration of listeners for the data to be indexed
** registration of jobs for the data to be re-indexed
** search service to use Elasticsearch (Jest via Spring Boot integration or REST client, tbd)
** refactoring of the search results page
** possibility of type-ahead search
** token based research as a default - more complex searches could be done later

**Comment by MorganGeek** [comment]
Nice !
