### ISSUE TITLE
The hyperlinks are not rendered in promotion / validation descriptions

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#748]
Example below : 
I've edited the description of a promotion level to point it to our internal documentation, and the hyperlink is not rendered <img width="1072" alt="promotions_ontrack_hyperlinks" src="https://user-images.githubusercontent.com/3721240/76516987-bf736100-645c-11ea-8d5e-41d151d3b823.png">

**Comment by dcoraboeuf** [comment]
Remaining, description in following pages:

* [ ] Project page
* [ ] Branch page
* [ ] Promotion level page
* [ ] Validation stamp page
* [ ] Build page
* [ ] Promotion run in build page

**Comment by MorganGeek** [comment]
I'm looking forward to this ! :)
