### ISSUE TITLE
Filters > builds to display can block ontrack

### ISSUE THREAD

**Issue by Pinio31** [nemerosa/ontrack#752]
I facing issue when I want to see all my builds on a single page, to reproduce:

**Ontrack version: 3.41.5**

**Steps:**
1. Go to your branch board and try to create any filter. 
2. Set:
a) Maximum count (try use as big value as you can, for my case, it was 10_000 with around 20 stamps per build, remember to reproduce it you need a lot of historical builds also)
b) Build from/to
3. Apply filter

**Results:**
1. Page render infinity "Loading the builds..." information
2. The page is broken, you can't use it anymore
3. Performance of the Ontrack possible drop down

<img width="1676" alt="screen" src="https://user-images.githubusercontent.com/43466107/76731656-390d9680-675e-11ea-99e8-84daeced127d.png">

**Temporary workaround:**
1. Open browser
2. Go to Application Tab
3. Local Storage
4. Remove value related with Ontrack site

**Comment by dcoraboeuf** [comment]
Thanks @Pinio31 , I will put a hard limit on 1000 (configurable in the static settings). Not planned yet, but one day, I'll make this view scrollable.
