### ISSUE TITLE
Missing image content on page

### ISSUE THREAD

**Issue by Pinio31** [nemerosa/ontrack#753]
**Ontrack version: 3.41.5**

**Steps**
1. Open any page

**Results:**
1. Missing content, response code 404
- {ontrackHost}/extension/{{otSearchBox.selectedSearchResultType.feature.id}}/search-icon/{{otSearchBox.selectedSearchResultType.id}}.png
- {ontrackHost}/extension/{{type.feature.id}}/search-icon/{{type.id}}.png

<img width="870" alt="issue" src="https://user-images.githubusercontent.com/43466107/76732055-0a43f000-675f-11ea-9656-9733570b1029.png">

**Comment by dcoraboeuf** [comment]
Yes, I've seen this. I think it's a side effect of the AngularJS templating, but nothing blocking. Still, better to fix this.

**Comment by dcoraboeuf** [comment]
Hi, I'll close this ticket (it was not forgotten :) ) and refocus on #1104 .
