### ISSUE TITLE
Getting the list of favourite branches takes too long

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#754]
In big setup with thousands of branches, getting the favourite branches takes way too much time, even if there are none. This has a big impact on the home page performances.

The following query allows to reproduce the performance issues:

```
{
  branches(favourite: true) {
    id
    name
  }
}
```

**Comment by dcoraboeuf** [comment]
cc. @MorganGeek

**Comment by MorganGeek** [comment]
Nice ! Thanks for handling this ! Will be a big improvement

**Comment by dcoraboeuf** [comment]
Added some indexes + optimization of getting the branches favourites

From 36 seconds to 3 seconds now on 10000+ branches

**Comment by MorganGeek** [comment]
Wow ! Such a massive increase of performance :-)

**Comment by dcoraboeuf** [comment]
Yep... I'm working now on project favourites. Less sensible but still. Note that the perf above are measured on my machine, it's usually already faster when running on a server.

**Comment by dcoraboeuf** [comment]
I have adapted the project favourite query as well, but as foreseen, this does not change much. I'll check if I can win more time still.

**Comment by dcoraboeuf** [comment]
Interesting fact. If I get _only_ the list of projects:

```
{
  projects {
    id
    name
  }
}
```

then I get an immediate answer (~ 20 ms) but if I had one link (even the simplest one):

```
{
  projects {
    id
    name
    links {
      _self
    }
  }
}
```

I get 100 x the time :( about 2 seconds. I think we can do better :)

**Comment by dcoraboeuf** [comment]
Hmmm, went from 2 seconds to 50 ms... for the GraphQL query above with 200+ projects...

The home page now displays in < 7 seconds

**Comment by dcoraboeuf** [comment]
To optimise still:

* `net.nemerosa.ontrack.service.ProjectFavouriteServiceImpl#isProjectFavourite`
* `net.nemerosa.ontrack.boot.ui.RelativeURIBuilder#build` but it relies on `org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder#fromMethodCall(org.springframework.web.util.UriComponentsBuilder, java.lang.Object)` which is known to be slugish. Unfortunately, I don't see how I could make this faster...

**Comment by dcoraboeuf** [comment]
Strange regressions on SVN integration tests. Fixing them...

**Comment by MorganGeek** [comment]
Thank you @dcoraboeuf  :)
