### ISSUE TITLE
promotion levels page needs pagination

### ISSUE THREAD

**Issue by NielsDoucet** [nemerosa/ontrack#786]
The promotion levels page should have some pagination in order to improve load times and make the information more easily digestible.
As an extra bonus, filtering by date and version would make it easier to track down a certain build within the list.

**Comment by dcoraboeuf** [comment]
Reopening. Pagination is in place, filtering is ready but not used.

**Comment by dcoraboeuf** [comment]
Remaining:

* [ ] Filter on build name
* [ ] Filter on build release property (version)
* [ ] UI fields to feed these filters
* [ ] UI pagination

**Comment by dcoraboeuf** [comment]
Available in 4.0.30
