### ISSUE TITLE
Notifications of releases on Gitter

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack#804]
Upon a release, notify it on Gitter (including release notes)

**Comment by MorganGeek** [comment]
Automate all the things ! :-)

**Comment by dcoraboeuf** [comment]
I already have the information in the release page on GitHub, so it's "just" a matter of sending this information in Gitter.

I still wonder, though, if Gitter is the way to go... But that's another story.

**Comment by MorganGeek** [comment]
Gitter might be one way to go for the people already contributing to Ontrack :-) , now about making more people aware of the tool, I would additionally target Twitter, that's a different thing but the power of retweets can really help :-)

**Comment by dcoraboeuf** [comment]
I think I'd keep Twitter for major releases (3.42 --> 3.43) and keep Gitter for everything else (3.42.11 -> 3.42.12)

**Comment by dcoraboeuf** [comment]
... or Twitter for everything as well
