### ISSUE TITLE
Calling ontrack from Jenkins using OntrackDSLStep

### ISSUE THREAD

**Issue by raj333921** [nemerosa/ontrack#813]
Using below snippet we are not able to generate *Use the provided DSL script* in Jenkins
![image](https://user-images.githubusercontent.com/6533418/93470769-b2936680-f8f2-11ea-8747-89e21dfe7f43.png)4
![image](https://user-images.githubusercontent.com/6533418/93471183-51b85e00-f8f3-11ea-925e-31c3322f3487.png)

How can i make usingText to true by using ontrackDSLStep?
Plugin version: ontrack@3.4.1
![image](https://user-images.githubusercontent.com/6533418/93472182-9d1f3c00-f8f4-11ea-93f3-85c6e44c5806.png)

But if i use below configuration, I am able to see the content as per expected.
configure { node ->
            node / builders / 'net.nemerosa.ontrack.jenkins.OntrackDSLStep' {
                usingText true
                injectEnvironment 'BRANCH'
                injectProperties ''
                ontrackLog true
                sandbox false
                ignoreFailure false
                scriptText '''println "BRANCH = ${BRANCH}"

def myBranch = "${BRANCH}"
if (myBranch.startsWith('branches/')) {
  myBranch = myBranch - 'branches/'
}
myBranch = myBranch.replaceAll('/', '-')

def ontrackBranch = myBranch
if (ontrackBranch.endsWith('x')) {
  ontrackBranch = ontrackBranch - 'x'
}

**Comment by dcoraboeuf** [comment]
Hi @raj333921 , it's more a defect for jenkinsci/ontrack-plugin ? Can you move this issue over there? Thanks

**Comment by raj333921** [comment]
Its in wrong place , I am rejecting this defect
