### ISSUE TITLE
Searching via Git commit only support long commit hashes

### ISSUE THREAD

**Issue by MorganGeek** [nemerosa/ontrack#819]
Running with Ontrack v3.43.1

Search made using short commit hash : 
<img width="1016" alt="short-hash" src="https://user-images.githubusercontent.com/3721240/98680021-208f6380-2361-11eb-882e-dcb77875e33a.png">

Search made using long commit hash for the same commit:
<img width="1051" alt="long-hash" src="https://user-images.githubusercontent.com/3721240/98680026-22f1bd80-2361-11eb-8e02-1d3753c761c0.png">

Are the short commit hashes indexed ?

**Comment by dcoraboeuf** [comment]
The short commit above does not look like an abbreviated commit, way too long. Might be worth to compare to the one returned by the Git API/command line.

**Comment by dcoraboeuf** [comment]
I've added an automated test (see commit fc50005 above) and I've also tested this use case manually. Both return results based on short commit searches.

My guess is that the abbreviated commit as shown in your example `ade57f5653f` is not compliant with what Git (command line or its API) would return, more like `ade57f5`.

I could add a fuzzy search factor on the search to take into account the fact that some commits might be different.

**Comment by dcoraboeuf** [comment]
Available in 3.43.3 - test only (see explanation above)

**Comment by MorganGeek** [comment]
Thanks for the feedback, well the abbreviated commit I've mentioned is the format used in Bitbucket, 11 characters, and indeed that's not the same as the 7 digits/characters commit hash we find in other platforms. That explains the confusion, sadly the short commit is what we see first in Bitbucket UI.

**Comment by dcoraboeuf** [comment]
Yes, that's pretty weird. I don't know if there is an "official" way to abbreviate commit hashes. In Ontrack, I take the one returned by Git itself.

**Comment by MorganGeek** [comment]
It seems it's configurable depending on projects, some big repos maintainers have chosen to use longer hashes because the short hash would cause collisions, as in the Linux project, more background https://stackoverflow.com/questions/18134627/how-much-of-a-git-sha-is-generally-considered-necessary-to-uniquely-identify-a
