### ISSUE TITLE
indicators portfolio > summary view with applicable with selected categories only

### ISSUE THREAD

**Issue by Majea** [nemerosa/ontrack#820]
I like the summary view we have when opening the indicator portfolios page. However, that page only uses the global indicators selection. Some may no apply to a specific portfolio. I would rather use the global indicators as defaults instead of showing them all in the main page.

**Comment by dcoraboeuf** [comment]
Given the scope of this feature, moving it to version 4.

**Comment by dcoraboeuf** [comment]
Available in 4.0.18
