### ISSUE TITLE
indicator portfolios > show the summary report on top of a portfolio details page

### ISSUE THREAD

**Issue by Majea** [nemerosa/ontrack#821]
I like the way the portfolios main page shows a summary of each portfolio. I would like to see that summary on of the page of a specific portfolio the same way as it is on the main page. Today, the summary isn't emphasised enough compared to the projects summaries.

**Comment by dcoraboeuf** [comment]
Hi @Majea ,

Would that change be OK?

![image](https://user-images.githubusercontent.com/1206964/127839030-27a8104e-aa05-4b6c-9578-b4c785d83acb.png)

**Comment by Majea** [comment]
LGTM. Thanks @dcoraboeuf

**Comment by dcoraboeuf** [comment]
Available in 4.0.19
