### ISSUE TITLE
onTrack InfluxDB metrics integration

### ISSUE THREAD

**Issue by GrimWit247** [nemerosa/ontrack#879]
I am using onTrack 3.43.4 the InfluxDB properties have been enabled , admin-health shows influxDBExtension and influxDb as “UP”

The following properties have also been enabled, “ontrack.influxdb.validation-data” and “ontrack.influxdb.run-info”

 After running in this way for a week, the only measurement I get into InfluxDB is “ontrack_value_run_info_build_time_seconds”. This confirms the connection works.

Is there something simple I’m missing to get run data into influxdb?

**Comment by dcoraboeuf** [comment]
Hi @GrimWit247 ,

I'd suggest first upgrading to the latest 3.43.x (.4 is pretty old, .19 has been released today). Especially because many issues with InfluxDB have been solved recently.

The run info build times are expected, that's good, but I'm not sure to understand by exporting the run data? What do you expect exactly to see?

Thanks,
Damien

**Comment by GrimWit247** [comment]
I was following this section of the documentation:



When an InfluxDB connector is correctly set, some Ontrack information is automatically sent to create timed values:
run info
validation run data

My intention is to collect  https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#validation-runs-data-metrics (general metrics and general metrics about jobs). 

I'll mention to benefits of upgrading to individual responsible for onTrack within my org. I'm purely responsible for monitoring SDLC as a whole.

**Comment by GrimWit247** [comment]
we have upgraded to  latest stable (v3.43.22), Influx is now shown in the UI, status shows "UP"

Should i expect to see the following metrics within influx:


Statistics about the objects stored by Ontrack:

    ontrack_entity_project_total (gauge) - total number of projects
    ontrack_entity_branch_total (gauge) - total number of branches
    ontrack_entity_build_total (gauge) - total number of builds
    ontrack_entity_promotionLevel_total (gauge) - total number of promotion levels
    ontrack_entity_promotionRun_total (gauge) - total number of promotion runs
    ontrack_entity_validationStamp_total (gauge) - total number of validation stamps
    ontrack_entity_validationRun_total (gauge) - total number of validation runs
    ontrack_entity_validationRunStatus_total (gauge) - total number of validation run statuses
    ontrack_entity_property_total (gauge) - total number of properties
    ontrack_entity_event_total (gauge) - total number of events

**Comment by dcoraboeuf** [comment]
Hi @GrimWit247 ,

The `ontrack_value_run_info_*` metrics will appear as soon as a build or validation run is created and associated with some run info (which is automatically the case if using the Ontrack Jenkins plug-in for example). 

The `ontrack_value_validation_data` will appear as soon as a validation run is created and associated with some data.

The `ontrack_entity_*` metrics are not exported by default to InfluxDB (unless you configure Spring Boot to do so), but they are available in the Prometheus endpoint.
